-- Switch document_chunks.embedding from 1536 dims (OpenAI text-embedding-3-small,
-- via the removed Lovable AI Gateway) to 768 dims (Gemini gemini-embedding-001,
-- truncated from its native 3072 dims via output_dimensionality — pgvector's
-- HNSW index caps out at 2000 dims, so the full 3072 isn't indexable).
--
-- Existing embeddings are OpenAI vectors and are not compatible with the new
-- model's vector space, and cannot be resized in place — they must be deleted
-- and regenerated by re-uploading/reprocessing the source documents.

-- 1. Drop the HNSW index (its dimension is baked in with the column).
DROP INDEX IF EXISTS public.document_chunks_embedding_idx;

-- 2. Remove existing chunks — they are the wrong dimension AND the wrong
--    embedding space, so they cannot be migrated in place.
TRUNCATE public.document_chunks;

-- 3. Resize the column to match Gemini's gemini-embedding-001 output, truncated
--    to 768 dims via output_dimensionality (see ingestDocument/embedQuery).
ALTER TABLE public.document_chunks
  ALTER COLUMN embedding TYPE vector(768);

-- 4. Recreate the HNSW index for the new dimension.
CREATE INDEX document_chunks_embedding_idx
  ON public.document_chunks USING hnsw (embedding vector_cosine_ops);

-- 5. Recreate match_chunks with the new query vector dimension.
CREATE OR REPLACE FUNCTION public.match_chunks(
  query_embedding vector(768),
  match_count int DEFAULT 5,
  owner_id uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  document_id uuid,
  chunk_index int,
  content text,
  similarity float
)
LANGUAGE sql STABLE SECURITY INVOKER
SET search_path = public
AS $$
  SELECT c.id, c.document_id, c.chunk_index, c.content,
         1 - (c.embedding <=> query_embedding) AS similarity
  FROM public.document_chunks c
  WHERE (owner_id IS NULL OR c.user_id = owner_id)
  ORDER BY c.embedding <=> query_embedding
  LIMIT match_count
$$;
GRANT EXECUTE ON FUNCTION public.match_chunks(vector, int, uuid) TO authenticated;

-- 6. Existing documents no longer have any chunks — flag them so the UI
--    prompts re-upload instead of showing a stale "ready" state with 0 chunks.
UPDATE public.documents
SET status = 'failed',
    error = 'Embedding model changed (OpenAI -> Gemini). Please re-upload this document.',
    chunk_count = 0
WHERE status = 'ready';
